Repository michmich112/teleporter, pull requests merged in 2021-02, with the labels that each got.

#3 Fastest way to take a dump
  README.md
  teleport.js
Labels: enhancement

#4 Fix shitting feature
  README.md
  teleport.js
Labels: bug, enhancement

#8 Aint no place like 127.0.0.1
  README.md
  teleport.js
Labels: enhancement

#10 added version update automation and set version to 0.2.0
  .github/workflows/versioning.yml
  manifest.json
  versioning-conf.json
Labels: documentation, enhancement

#11 you can shit wherever you want. handles issue #5
  README.md
  teleport.js
Labels: documentation, enhancement

#15 ft/teleport to player ui
  README.md
  inject.js
  manifest.json
  player-ui.js
  teleport.js
Labels: enhancement
